
version: "2.4"

services:

  restfm:
    build:
      context: .
      dockerfile: Dockerfile.RESTfm
      args:
        USER_ID: ${USER_ID:-500}
        GROUP_ID: ${GROUP_ID:-500}
        PHP_VERSION: ${PHP_VERSION:-8.1}
        CERT_CN: ${CERT_CN:-localhost}
    image: "restfm-php${PHP_VERSION}"
    container_name: restfm
    hostname: restfm
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    #environment:
    volumes:
      - ./files/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./files/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ../..:/var/www/html/RESTfm
      - ./files/RESTfm/conf.d:/var/www/html/RESTfm/conf.d
    ports:
      - 8870:80
      - 8470:443

  filemaker:
    build:
      context: .
      dockerfile: Dockerfile.FileMaker
      args:
        USER_ID: ${USER_ID:-500}
        GROUP_ID: ${GROUP_ID:-500}
    image: filemaker
    container_name: filemaker
    hostname: filemaker
    restart: unless-stopped
    #environment:
    volumes:
      - /export/gavin/docker/bind-mounts/snakepit-chia/home-chia-pooled:/home/chia
      - /export/gavin/docker/bind-mounts/snakepit-chia/mnt:/mnt:ro
    ports:
      - 8820:80
      - 8420:443
      - 2399:2399
      - 5003:5003
